language: node_js
services:
  - mongodb
os:
  - linux
node_js:
  - 10.15.1
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
install:
  - npm install
  - npm install mocha@6.1.4 -g
script:
  - mocha --exit